package models

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

// Organization represents a single Radio Station (Tenant)
type Organization struct {
	ID          uuid.UUID      `gorm:"type:uuid;primaryKey;default:gen_random_uuid()" json:"id"`
	Name        string         `gorm:"not null" json:"name"`
	StationSlug string         `gorm:"type:varchar(50);uniqueIndex;not null" json:"station_slug"` // e.g., "concrete-radio"
	StreamKey   string         `gorm:"type:varchar(100);uniqueIndex;not null" json:"stream_key"`  // e.g., "live_948201_x9f2ba9e"
	Plan        string         `gorm:"default:'free'" json:"plan"`                                // free, pro, enterprise
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	DeletedAt   gorm.DeletedAt `gorm:"index" json:"-"`

	// Relationships
	Members     []OrganizationUser `json:"members,omitempty"`
	MountPoints []MountPoint       `json:"mount_points,omitempty"`
}

// User replaces the legacy Users table. ID must match Supabase auth.users.id
type User struct {
	ID        uuid.UUID `gorm:"type:uuid;primaryKey" json:"id"`
	Email     string    `gorm:"uniqueIndex;not null" json:"email"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`

	Organizations []OrganizationUser `json:"organizations,omitempty"`
}

// OrganizationUser is the RBAC pivot table
type OrganizationUser struct {
	OrganizationID uuid.UUID `gorm:"type:uuid;primaryKey" json:"organization_id"`
	UserID         uuid.UUID `gorm:"type:uuid;primaryKey" json:"user_id"`
	Role           string    `gorm:"type:varchar(20);not null;default:'viewer'" json:"role"` // owner, admin, dj, viewer

	Organization Organization `gorm:"foreignKey:OrganizationID" json:"organization,omitempty"`
	User         User         `gorm:"foreignKey:UserID" json:"user,omitempty"`
}

// MountPoint represents a specific HLS/Icecast streaming configuration for an Organization
type MountPoint struct {
	ID             uuid.UUID      `gorm:"type:uuid;primaryKey;default:gen_random_uuid()" json:"id"`
	OrganizationID uuid.UUID      `gorm:"type:uuid;not null;uniqueIndex:idx_org_mount_slug" json:"organization_id"`
	Name           string         `gorm:"type:varchar(100);not null" json:"name"`                               // e.g., "High Quality Stream"
	Slug           string         `gorm:"type:varchar(50);not null;uniqueIndex:idx_org_mount_slug" json:"slug"` // e.g., "radio", "mobile"
	Bitrate        int            `gorm:"not null" json:"bitrate"`                                              // e.g., 320, 128, 64
	IsDefault      bool           `gorm:"default:false" json:"is_default"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
	DeletedAt      gorm.DeletedAt `gorm:"index" json:"-"`

	// HlsUrl is dynamically generated by the handler based on the Organization's StationSlug.
	// The gorm:"-" tag ensures GORM ignores this field when interacting with the database.
	HlsUrl string `gorm:"-" json:"hls_url,omitempty"`
}
