package models

import (
	"testing"

	"github.com/google/uuid"
	"github.com/stretchr/testify/assert"
	"gorm.io/driver/postgres"
	"gorm.io/gorm"

	"momo-radio/internal/testutils"
)

func setupTenantTestDB(t *testing.T) *gorm.DB {
	t.Helper()
	connStr := testutils.SetupPostgres(t)
	db, err := gorm.Open(postgres.Open(connStr), &gorm.Config{})
	assert.NoError(t, err)

	// Migrate the multi-tenancy models
	err = db.AutoMigrate(
		&Organization{},
		&User{},
		&OrganizationUser{},
		&MountPoint{},
		&OrganizationSettings{},
	)
	assert.NoError(t, err)

	return db
}

func TestTenantModelsIntegration(t *testing.T) {
	db := setupTenantTestDB(t)

	var orgID uuid.UUID
	var userID uuid.UUID

	t.Run("Create Tenant Graph", func(t *testing.T) {
		userID = uuid.New()

		user := User{
			ID:    userID,
			Email: "dj@concrete-radio.com",
			Name:  "Main DJ",
		}

		// Organization ID is generated by Postgres via gen_random_uuid()
		org := Organization{
			Name:        "Concrete Radio",
			StationSlug: "concrete-radio",
			StreamKey:   "live_12345_abc",
		}

		// 1. Insert User and Org
		assert.NoError(t, db.Create(&user).Error)
		assert.NoError(t, db.Create(&org).Error)

		orgID = org.ID
		assert.NotEqual(t, uuid.Nil, orgID, "Organization ID should have been auto-generated by DB")

		// 2. Link them via the pivot table with a role
		orgUser := OrganizationUser{
			OrganizationID: org.ID,
			UserID:         user.ID,
			Role:           "owner",
		}
		assert.NoError(t, db.Create(&orgUser).Error)

		// 3. Add a MountPoint
		mount := MountPoint{
			OrganizationID: org.ID,
			Name:           "High Quality",
			Slug:           "hq",
			Bitrate:        320,
			IsDefault:      true,
		}
		assert.NoError(t, db.Create(&mount).Error)

		// 4. Add OrganizationSettings
		settings := OrganizationSettings{
			OrganizationID: org.ID,
			StationName:    "Concrete Underground",
			Timezone:       "Europe/Paris",
		}
		assert.NoError(t, db.Create(&settings).Error)
	})

	t.Run("Unique Constraints", func(t *testing.T) {
		// Attempt to create a MountPoint with the same slug ('hq') for the SAME organization
		dupMount := MountPoint{
			OrganizationID: orgID,
			Name:           "Another HQ stream",
			Slug:           "hq",
			Bitrate:        128,
		}
		err := db.Create(&dupMount).Error
		assert.Error(t, err, "expected unique constraint violation on idx_org_mount_slug")

		// Attempt to create an Organization with an existing station_slug
		dupOrg := Organization{
			Name:        "Copycat Radio",
			StationSlug: "concrete-radio",
			StreamKey:   "live_99999_xyz",
		}
		err = db.Create(&dupOrg).Error
		assert.Error(t, err, "expected unique constraint violation on station_slug")
	})

	t.Run("Preload Tenant Data", func(t *testing.T) {
		var fetchedOrg Organization

		// Fetch the Organization and preload its entire relationship tree
		err := db.Preload("MountPoints").
			Preload("Members").      // Loads the OrganizationUser pivot
			Preload("Members.User"). // Nested preload: loads the actual User struct inside the pivot
			Where("station_slug = ?", "concrete-radio").
			First(&fetchedOrg).Error

		assert.NoError(t, err)
		assert.Equal(t, "Concrete Radio", fetchedOrg.Name)

		// Verify MountPoints
		assert.Len(t, fetchedOrg.MountPoints, 1)
		assert.Equal(t, "hq", fetchedOrg.MountPoints[0].Slug)
		assert.True(t, fetchedOrg.MountPoints[0].IsDefault)

		// Verify RBAC and Pivot Loading
		assert.Len(t, fetchedOrg.Members, 1)
		assert.Equal(t, "owner", fetchedOrg.Members[0].Role)
		assert.Equal(t, "dj@concrete-radio.com", fetchedOrg.Members[0].User.Email)
		assert.Equal(t, "Main DJ", fetchedOrg.Members[0].User.Name)
	})
}
