services:
  postgres:
    image: postgres:15-alpine
    container_name: radio_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=radio
      - POSTGRES_PASSWORD=radiopassword
      - POSTGRES_DB=radio
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U radio"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: radio_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
  asynqmon:
    image: hibiken/asynqmon:latest
    platform: linux/amd64
    container_name: radio_asynqmon
    restart: unless-stopped
    ports:
      - "8090:8080"
    command: ["--redis-addr=redis:6379"]
    depends_on:
      - redis

volumes:
  db_data:
  redis_data: